apiVersion: v1
entries:
  traefik:
  - apiVersion: v2
    appVersion: 2.5.3
    created: "2021-10-20T19:10:26.218751+05:30"
    description: A Traefik based Kubernetes ingress controller
    digest: db8f7e24e39522ed3cce3dcd3866f9fc4a92b43a429e0663837deea943f276d5
    home: https://traefik.io/
    icon: https://raw.githubusercontent.com/traefik/traefik/v2.3/docs/content/assets/img/traefik.logo.png
    keywords:
    - traefik
    - ingress
    maintainers:
    - email: emile@vauge.com
      name: emilevauge
    - email: daniel.tomcej@gmail.com
      name: dtomcej
    - email: ldez@traefik.io
      name: ldez
    name: traefik
    sources:
    - https://github.com/traefik/traefik
    - https://github.com/traefik/traefik-helm-chart
    type: application
    urls:
    - https://github.com/ssarbadh/traefik-helm-chart/traefik/traefik-10.6.0.tgz
    version: 10.6.0
generated: "2021-10-20T19:10:26.216827+05:30"
